on: push

name:  Node.js CI/CD Pipeline 

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'  
        
      - name: Install Dependencies
        run: npm install

      - name: Build Docker Image
        run: docker build -t izzmoqbel/devops_project .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  
          password: ${{ secrets.DOCKER_PASSWORD }} 

      - name: Push Docker Image to Docker Hub
        run: docker push izzmoqbel/devops_project:latest