name: Release

on:
  push:
    tags:
      - '**'  

env:
  DOCKER_REPO: izzmoqbel/devops_project  

jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }} 
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build Docker Image
        run: |
          version=${GITHUB_REF##*/}
          docker build . -t $DOCKER_REPO:$version

      - name: Push Docker Image
        run: |
          version=${GITHUB_REF##*/}
          docker push $DOCKER_REPO:$version
          echo "\`docker run -p 3000:3000 $DOCKER_REPO:$version\`" > release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.G_TOKEN }} 
          body_path: release